name: GitHub Actions Demo
on: [workflow_dispatch]
jobs:
    build:
        # ...
        runs-on: ubuntu-latest
        steps:

         - name: Check out the repo
           uses: actions/checkout@v2

         - name: Get short SHA
           run: echo "GHA_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v1

         - name: Build
           uses: docker/build-push-action@v2
           with:
             tags: my-tweet-app-lacework:${{ env.GHA_SHA }}
             load: true

         - name: lw-scanner
           uses: timarenz/lw-scanner-action@v0.2.2
           env:
             LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
             LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
           with:
             image_name: my-tweet-app-lacework
             image_tag: ${{ env.GHA_SHA }}
             fail_only_if_vulnerabilities_fixable: true
             scan_library_packages: true
